 "use client";
import {useMemo,useState} from "react";import {demoEmployees} from "@/lib/demo-data";import {Employee} from "@/lib/types";
import { supabase } from "@/lib/supabase";import {Search,Plus,X} from "lucide-react";
export default function EmployeeManager(){const[es,setEs]=useState<Employee[]>([]);
const[loading,setLoading]=useState(true);const[q,setQ]=useState("");const[open,setOpen]=useState(false);const[f,setF]=useState<any>({name:"",email:"",phone:"",department:"",designation:"",joiningDate:"",status:"Active"});
const filtered=useMemo(()=>es.filter(e=>`${e.name} ${e.email} ${e.department} ${e.designation}`.toLowerCase().includes(q.toLowerCase())),[es,q]);
useEffect(()=>{(async()=>{const {data,error}=await supabase.from("employees").select("*").order("created_at",{ascending:true});if(!error&&data)setEs(data as any);setLoading(false)})()},[]);
async function add(){if(!f.name||!f.email)return;const n=es.length+1;const parts=f.name.trim().split(/\s+/);const first=(parts[0]||"employee").toLowerCase();const initial=parts.length>1?parts[parts.length-1][0].toLowerCase():"x";const employee_id=`${first}.${initial}.${n}`;const {data,error}=await supabase.from("employees").insert({employee_id,full_name:f.name,email:f.email,phone:f.phone,department:f.department,designation:f.designation,joining_date:f.joiningDate,status:f.status}).select().single();if(error){alert(error.message);return}setEs(x=>[...x,data as any]);setF({name:"",email:"",phone:"",department:"",designation:"",joiningDate:"",status:"Active"});setOpen(false)}
return <div><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold">Employees</h1><p className="mt-1 text-sm text-neutral-500">Manage employee profiles and HR information.</p></div><button className="btn-dark flex items-center gap-2" onClick={()=>setOpen(true)}><Plus size={17}/>Add Employee</button></div>
<div className="card overflow-hidden"><div className="border-b border-black/5 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 text-neutral-400" size={17}/><input className="input pl-10" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search employees..."/></div></div>{loading?<div className="p-8 text-center text-sm text-neutral-500">Loading employees...</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Designation</th><th className="px-5 py-3">Joining</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} className="border-t border-black/5"><td className="px-5 py-4"><b>{e.name}</b><div className="text-xs text-neutral-500">{e.id} · {e.email}</div></td><td className="px-5 py-4">{e.department}</td><td className="px-5 py-4">{e.designation}</td><td className="px-5 py-4">{e.joiningDate}</td><td className="px-5 py-4"><span className="rounded-full bg-green-50 px-2.5 py-1 text-xs font-semibold text-green-700">{e.status}</span></td></tr>)}</tbody></table></div>}
</div>
{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="card max-h-[90vh] w-full max-w-2xl overflow-auto p-6"><div className="mb-6 flex justify-between"><h2 className="text-xl font-bold">Add Employee</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{[["name","Full Name","text"],["email","Email","email"],["phone","Phone","tel"],["department","Department","text"],["designation","Designation","text"],["joiningDate","Joining Date","date"]].map(([k,l,t])=><div key={k}><label className="label">{l}</label><input className="input" type={t} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}<div><label className="label">Status</label><select className="input" value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Active</option><option>On Notice</option><option>Resigned</option></select></div></div><div className="mt-6 flex justify-end gap-2"><button className="btn-light" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-dark" onClick={add}>Save Employee</button></div></div></div>}</div>}